### ISSUE TITLE
Crash when trying to retrieve attributes on an external volume

### ISSUE THREAD

**Issue by v8oholic** [RhetTbull/osxmetadata#118]
Apologies if this has been covered before, but I couldn't see any mention of it. I have just installed osxmetadata and I am experimenting with it, but I have hit a problem straight away.

I have files on an external volume which I am trying to read the attributes for. However, it crashes when creating MDItem for the file:

```
(tagtest) steve@MacBook-Air FFRunner % python -m osxmetadata -l /Volumes/Music/Temp/test-9026.mp4

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/osxmetadata/__main__.py", line 1164, in <module>
    cli()  # pylint: disable=no-value-for-parameter
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/osxmetadata/__main__.py", line 989, in cli
    process_files(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/osxmetadata/__main__.py", line 1080, in process_files
    process_single_file(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/osxmetadata/__main__.py", line 1120, in process_single_file
    md = OSXMetaData(fpath)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/facefusion/lib/python3.10/site-packages/osxmetadata/osxmetadata.py", line 96, in __init__
    raise OSError(f"Unable to create MDItem for file: {fname}")
OSError: Unable to create MDItem for file: /Volumes/Music/Temp/test-9026.mp4
(tagtest) steve@MacBook-Air FFRunner %
```

If I copy the same file onto the main hard disk (using finder), then it works fine:

```
(tagtest) steve@MacBook-Air FFRunner % python -m tagtest -l test-9026.mp4
/Users/steve/Applications/Python/tagtest/test-9026.mp4:
tags                      _kMDItemUserTags                  = Orange: 7
findercolor               findercolor                       = 7
attributechangedate       kMDItemAttributeChangeDate        = 2024-11-22T10:53:08.839543
audiobitrate              kMDItemAudioBitRate               = 160.0
audiochannelcount         kMDItemAudioChannelCount          = 2.0
codecs                    kMDItemCodecs                     = H.264, MPEG-4 AAC

...

stationerypad             stationerypad                     = False
(tagtest) steve@MacBook-Air FFRunner % 
```

Obviously I can't copy every file from the external disk, there isn't the space. Is there something I am not doing right? Is it a known problem?

It's Python 3.10.14 on Sequoia 15.1.1 and python does have access to external volumes.

I can provide any further information that I may have missed, just let me know. Thanks!

**Comment by v8oholic** [comment]
I have been able to read the attributes of the file on the external volume (com.apple.FinderInfo and com.apple.metadata:_kMDItemUserTags) using xattr. Both command line, and in python. Perhaps they don't use MDItemCreate internally, which is where osxmetatag is failing.

I haven't entirely worked out the format of the colour attributes, but I have managed a horrible hack which will filter the files according to colour tags, which is what I was trying to achieve. So for the moment I don't need to use osxmetadata. A bit weird and frustrating though.

**Comment by v8oholic** [comment]
Could this be a sandboxing issue? I'm not sure how that stuff works.

**Comment by RhetTbull** [comment]
I have been able to replicate this on Ventura. I do not have a machine running Sequoia. This is weird because previously on Ventura I was able to use OSXMetadata fine. (I pulled a command from my zsh history I'd previously used). 

OSXMetadata uses a private Apple API for most operations unlike xattr which uses a public OS level API. It is possible Apple has changed the private API or somehow restricted the private API to a private entitlement. If so, it is weird they'd do this for external drives and not internal. (I've seen them start doing this in Sequoia with other private APIs, in particular Photos, which I also use extensively in other projects). I will look into this as time permits to see if I can figure it out as OSXMetadata is an important part of my workflow. 

If you merely want to read the extended attributes then direct access to them via xattr works fine, in most cases, and earlier versions of OSXMetadata did this. However, in many cases, writing to the extended attributes does not update the actual  metadata in the Spotlight database. These are managed by the private API. Hence, OSXPhotos was rewritten to use the MDItemCreate API.

The code that is failing is in the call to [MDItemCreate](https://developer.apple.com/documentation/coreservices/1426917-mditemcreate) and this is a public API. The documentation does not indicate anything has changed. The  only private API access is used when writing attributes. The function may have been changed to require paths to external volumes in a different format. I will see if I can figure out what is going on.

**Comment by RhetTbull** [comment]
The code appears to work on mounted disk images and on mounted SMB shares. It only fails on directly attached external volumes which is very strange.

**Comment by RhetTbull** [comment]
So this appears to affect the native MacOS utility `mdls` as well:

```bash
❯ ls /Volumes/OWC_Backup/Photos/rhet/2024/10/14/IMG_0457_20241014.HEIC
 /Volumes/OWC_Backup/Photos/rhet/2024/10/14/IMG_0457_20241014.HEIC
(osxmetadata)
rhet in 🌐 Mac-mini in osxmetadata on  master [$?] is 📦 v1.4.0 via 🐍 v3.11.7 (osxmetadata)
❯ mdls /Volumes/OWC_Backup/Photos/rhet/2024/10/14/IMG_0457_20241014.HEIC
/Volumes/OWC_Backup/Photos/rhet/2024/10/14/IMG_0457_20241014.HEIC: could not find /Volumes/OWC_Backup/Photos/rhet/2024/10/14/IMG_0457_20241014.HEIC.
```

**Comment by v8oholic** [comment]
Thanks for looking into it. The inconsistency between native utilities and the API makes you wonder if it's unintentional, and maybe just a new bug that Apple have introduced into MDItemCreate. In which case it might be a while before it gets fixed.

**Comment by RhetTbull** [comment]
Yes, I think the bug is actually in `MDItemCreate`. I will [file a bug with Apple](https://developer.apple.com/bug-reporting/). It probably wouldn't hurt if you did as well. They won't care about a third-party open source app using a private API but if you can replicate the problem using `mdls` and file a bug report that would be helpful.

**Comment by luckman212** [comment]
@RhetTbull Can you provide your bug ID so we can reference it? I have heard that helps bump them up in priority.

**Comment by RhetTbull** [comment]
@luckman212 @v8oholic I submitted two bugs, one for `mdls` and one for `MDItemCreate` (referencing each other)

FB15951151 : MDItemCreate fails when instantiated with a path to file on a locally-mounted external disk
FB15951012 : mdls fails when run on a file located on an externally mounted disk

The following Objective-C code is a minimal example able to reproduce the issue (I included this with my bug report):

```objc
// reproduce bug in MDItemCreate which fails when path is on a mounted locally-connected external volume.
// build with: clang -framework Foundation -framework CoreServices -o MDItemUtility MDItemUtility.m

#import <Foundation/Foundation.h>
#import <CoreServices/CoreServices.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        if (argc != 2) {
            fprintf(stderr, "Usage: %s <path_to_file>\n", argv[0]);
            return 1;
        }

        const char *path = argv[1];
        NSString *filePath = [NSString stringWithUTF8String:path];

        if (![[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
            fprintf(stderr, "Error: File does not exist at the specified path: %s\n", path);
            return 1;
        }

        // Create an MDItem for the specified file
        MDItemRef item = MDItemCreate(kCFAllocatorDefault, (__bridge CFStringRef)filePath);
        if (item == NULL) {
            fprintf(stderr, "Error: Unable to create MDItem for file at path: %s\n", path);
            return 1;
        }

        // Get metadata attributes for the item
        CFArrayRef attributes = MDItemCopyAttributeNames(item);
        if (attributes == NULL) {
            fprintf(stderr, "Error: Unable to retrieve metadata attributes for file: %s\n", path);
            CFRelease(item);
            return 1;
        }

        printf("Metadata for file at path: %s\n", path);
        for (CFIndex i = 0; i < CFArrayGetCount(attributes); i++) {
            CFStringRef attributeName = CFArrayGetValueAtIndex(attributes, i);
            CFTypeRef attributeValue = MDItemCopyAttribute(item, attributeName);

            if (attributeValue != NULL) {
                NSString *attrName = (__bridge NSString *)attributeName;
                NSString *attrValue = [(__bridge id)attributeValue description];
                printf("%s: %s\n", [attrName UTF8String], [attrValue UTF8String]);
                CFRelease(attributeValue);
            }
        }

        // Clean up
        CFRelease(attributes);
        CFRelease(item);
    }
    return 0;
}
```

**Comment by luckman212** [comment]
Thanks @RhetTbull I will file adjunct reports, this is great info.

**Comment by mhnestler** [comment]
I think it is about the volume being excluded from Spotlight. I tested this on two APFS volumes, both on my internal SSD, both created by me, the only difference is one of them is not indexed (via Spotlight -> "Search Privacy" in System Settings). In the no-Spotlight volume, `osxmetadata --list myfile` fails with `OSError: Unable to create MDItem for file` as described above, and `mdls` also fails as described above; and in the yes-Spotlight volume, both succeed.

Furthermore, a different but related problem occurs with *folders* that are excluded from Spotlight (on volume *with* Spotlight enabled). In those cases, what happens is:

* `mdls` prints out minimal info, and doesn't print out xattrs such as kMDItemWhereFroms
* `osxmetadata` prints out nothing (but doesn't crash)
* `xattr` can still extract the data.
