### ISSUE TITLE
bug: timezone not handled properly

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxmetadata#17]
Operating System: OS X v10.11.6 El Capitan

osxmetadata is missing the timezone data from the 'com.apple.metadata:kMDItemDownloadedDate' xattr, which, at least with Safari 11.1.2 on El Capitan, always seems to be specified as 'Z' in the bplist (as per ISO 8601, Z specifies UTC time).

For example, my timezone is UTC-04:00.

I downloaded a file using Safari at 10:03 AM in my timezone, and looking at the com.apple.metadata:kMDItemDownloadedDate xattr on the file, the date is 2020-04-06T14:03:34Z (2:03:34 PM UTC), which makes perfect sense since my timezone is 4 hours behind UTC.

However, if I then modify the 'com.apple.metadata:kMDItemDownloadedDate' xattr using osxmetadata 11 minutes after downloading the file like so:

>>> md = osxmetadata.OSXMetaData("/path/to/file.jpg")
>>> md.downloadeddate
[datetime.datetime(2020, 4, 6, 14, 3, 34, 829270)]
>>> md.downloadeddate = [datetime.datetime.now()]
>>> md.downloadeddate
[datetime.datetime(2020, 4, 6, 10, 14, 1, 973745)]

Even though I changed the xattr to the current time (11 minutes into the future), the time specified in the xattr has effectively gone back almost four hours into the past!
From: 2020-04-06T14:03:34Z (2:03:34 PM UTC)
To: 2020-04-06T10:14:01Z (10:14:01 AM UTC)

Also worth noting, README.md in your git repo has a slight error when mentioning timezones here:

"kMDItemDownloadedDate, com.apple.metadata:kMDItemDownloadedDate; The date the item was downloaded.  A date in ISO 8601 format: e.g. 2000-01-12T12:00:00 or 2000-12-31 (ISO 8601 w/o time zone)"

Both of the dates listed there are missing the timezone. The only difference between them is that one has the time (12:00:00, unspecified timezone), and the other has no time.

**Comment by RhetTbull** [comment]
Some additional research on this:
kMDItemDownloadedDate is clearly stored as UTC by Apple:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<date>2020-04-07T03:53:35Z</date>
</array>
</plist>
```

However, plistlib returns the date as a timezone naive datetime.datetime object:
```python
>>> md.downloadeddate
[datetime.datetime(2020, 4, 7, 3, 53, 35, 378438)]
```
But setting time stores the local naive time as a UTC time (plistlib assumes the naive time is in UTC):
```python
>>> md.downloadeddate
[datetime.datetime(2020, 4, 7, 3, 53, 35, 378438)]
>>> md.downloadeddate = datetime.datetime.now()
>>> md.downloadeddate
[datetime.datetime(2020, 4, 6, 21, 8, 32, 156425)]
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<date>2020-04-06T21:08:32Z</date>
</array>
</plist>
```

```python
>>> datetime.datetime.utcnow()
datetime.datetime(2020, 4, 7, 4, 22, 9, 331464)
```

Local timezone is 7 hours behind UTC

Additionally, plistlib can't accept a timezone aware datetime object:

```python
>>> md.downloadeddate = datetime.datetime.now(timezone.utc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rhet/Dropbox/Code/osxmetadata/osxmetadata/__init__.py", line 459, in __setattr__
    self.set_attribute(attribute.name, value)
  File "/Users/rhet/Dropbox/Code/osxmetadata/osxmetadata/__init__.py", line 247, in set_attribute
    getattr(self, attribute.name).set_value(value)
  File "/Users/rhet/Dropbox/Code/osxmetadata/osxmetadata/classes.py", line 29, in set_value
    self._write_data()
  File "/Users/rhet/Dropbox/Code/osxmetadata/osxmetadata/classes.py", line 77, in _write_data
    plist = plistlib.dumps(self.data, fmt=FMT_BINARY)
  File "/Users/rhet/anaconda3/envs/osxmeta/lib/python3.8/plistlib.py", line 1019, in dumps
    dump(value, fp, fmt=fmt, skipkeys=skipkeys, sort_keys=sort_keys)
  File "/Users/rhet/anaconda3/envs/osxmeta/lib/python3.8/plistlib.py", line 1012, in dump
    writer.write(value)
  File "/Users/rhet/anaconda3/envs/osxmeta/lib/python3.8/plistlib.py", line 761, in write
    self._write_object(obj)
  File "/Users/rhet/anaconda3/envs/osxmeta/lib/python3.8/plistlib.py", line 885, in _write_object
    f = (value - datetime.datetime(2001, 1, 1)).total_seconds()
TypeError: can't subtract offset-naive and offset-aware datetimes
>>>```

**Comment by RhetTbull** [comment]
Additionally, fix should append time zone to the json file stored in --backup .json file:

```json
{"_version": "0.98.12", "_filepath": "/Users/rhet/Downloads/Test.txt", "_filename": "Test.txt", "com.apple.metadata:kMDItemDownloadedDate": ["2020-04-07T03:53:35.378438"],}
```

**Comment by RhetTbull** [comment]
Thinking about the fix:
1. convert datetime object read from plistlib to timezone aware object in UTC
2. when writing back to xattr, if datetime object is tz aware, convert to utc then to naive object and write that data out
3. If datetime object is naive, assume in local timezone, convert to UTC, then to naive object and write it out
4. store timezone info in the .json backup file: e.g. 2020-04-07T03:53:35.378438Z

**Comment by RhetTbull** [comment]
Also, plistlib should really be fixed to understand timezones!

**Comment by RhetTbull** [comment]
# convert from utc to local
from datetime import datetime, timezone

def utc_to_local(utc_dt):
    return utc_dt.replace(tzinfo=timezone.utc).astimezone(tz=None)

```python
>>> d = md.downloadeddate
>>> d
2020-04-13 09:28:00,319 - DEBUG - classes.py - 44 - data = [datetime.datetime(2020, 4, 13, 15, 46, 54, 902173)]
[datetime.datetime(2020, 4, 13, 15, 46, 54, 902173)]
>>> d[0].replace(tzinfo=timezone.utc).astimezone(tz=None)
2020-04-13 09:28:22,880 - DEBUG - classes.py - 44 - data = [datetime.datetime(2020, 4, 13, 15, 46, 54, 902173)]
datetime.datetime(2020, 4, 13, 8, 46, 54, 902173, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200), 'PDT'))
```

```python
# get local timezone
>>> local_tz = datetime.datetime.now(datetime.timezone(datetime.timedelta(0))).astimezone().tzinfo
>>>
```

```python
>>> local = d[0].replace(tzinfo=timezone.utc).astimezone(tz=None)
2020-04-13 09:32:46,039 - DEBUG - classes.py - 44 - data = [datetime.datetime(2020, 4, 13, 15, 46, 54, 902173)]
>>> local
datetime.datetime(2020, 4, 13, 8, 46, 54, 902173, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200), 'PDT'))
>>> local_tz = datetime.datetime.now(datetime.timezone(datetime.timedelta(0))).astimezone().tzinfo
>>> local_tz
datetime.timezone(datetime.timedelta(days=-1, seconds=61200), 'PDT')
>>> utc = local.replace(tzinfo=local_tz).astimezone(tz=timezone.utc)
>>> utc
datetime.datetime(2020, 4, 13, 15, 46, 54, 902173, tzinfo=datetime.timezone.utc)
>>>
```

**Comment by RhetTbull** [comment]
Have a working fix, now working on the test cases.  Still trying to decide if it's more intuitive to present results in offset naive or offset aware datetime.datetime objects.  Offset aware certainly preserves the most information but takes extra steps for the user to work with because you couldn't do things like this:
```python
>>> now = datetime.datetime.now()
>>> now
datetime.datetime(2020, 4, 14, 10, 38, 41, 633685)
>>> dld = md.downloadeddate
>>> dld
[datetime.datetime(2020, 4, 14, 17, 38, 10, 71968, tzinfo=datetime.timezone.utc)]
>>> now > dld[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't compare offset-naive and offset-aware datetimes
>>>
```

**Comment by RhetTbull** [comment]
I decided to have datetime attributes return timezone naive objects by default (but do appropriate conversions) and add a tz_aware property to OSXMetaData that if True, causes datetime attributes to return timezone aware objects.
