### ISSUE TITLE
Finder comment does not work on directories

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxmetadata#26]
The Finder can add comments to to a directory and osxmetadata can read these but osxmetadata fails when trying to write a comment.  Reading and writing tags does work.  Need to check other metadata.

```python
>>> from osxmetadata import OSXMetaData, Tag
>>> md = OSXMetaData("/users/rhet/Downloads")
>>> md.tags
[Tag('Blue', 4), Tag('test', 0)]
>>> md.findercomment
'Foo'
>>> md.findercomment = "Hello"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rhet/Dropbox/Code/osxmetadata/osxmetadata/osxmetadata.py", line 502, in __setattr__
    self.set_attribute(attribute.name, value)
  File "/Users/rhet/Dropbox/Code/osxmetadata/osxmetadata/osxmetadata.py", line 312, in set_attribute
    set_finder_comment(self._posix_name, value)
  File "/Users/rhet/Dropbox/Code/osxmetadata/osxmetadata/findercomments.py", line 34, in set_finder_comment
    raise FileNotFoundError(f"Could not find {filename}")
FileNotFoundError: Could not find /users/rhet/Downloads
```

**Comment by RhetTbull** [comment]
PR #29 fixes this but the command line tool still does not work.  It appears to (no error) but the comments / tags on directories don't actually get set.

Problem is here:
https://github.com/RhetTbull/osxmetadata/blob/113547385bfe5cab564ea9ec0be16db464ed9a69/osxmetadata/__main__.py#L456-L462

**Comment by RhetTbull** [comment]
@all-contributors please add @bglezseoane  for code
