### ISSUE TITLE
errors upon executing osxmetadata on Monterey

### ISSUE THREAD

**Issue by john-catalano** [RhetTbull/osxmetadata#54]
I'm fairly certain my issue not specific to osxmetadata, but I did follow the install instructions, and I am not familiar with troubleshooting python or pip/x, so I'm hoping someone, here, can help.

I am running the latest Monterey, the latest brew, and installed the latest command line tools.

When I run "osxmetadata" at my terminal, I get this output:

john@mac ~ % osxmetadata
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyobjc-core 7.2 (/usr/local/lib/python3.9/site-packages/pyobjc_core-7.2-py3.9-macosx-11-x86_64.egg), Requirement.parse('pyobjc-core>=7.3'), {'pyobjc-framework-Cocoa'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osxmetadata", line 33, in <module>
    sys.exit(load_entry_point('osxmetadata==0.99.14', 'console_scripts', 'osxmetadata')())
  File "/usr/local/bin/osxmetadata", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/osxmetadata-0.99.14-py3.9.egg/osxmetadata/__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/osxmetadata-0.99.14-py3.9.egg/osxmetadata/osxmetadata.py", line 16, in <module>
  File "/usr/local/lib/python3.9/site-packages/py_applescript-1.0.2-py3.9.egg/applescript/__init__.py", line 5, in <module>
    from Foundation import NSAppleScript, NSAppleEventDescriptor, NSURL, \
  File "/usr/local/lib/python3.9/site-packages/pyobjc_framework_Cocoa-7.3-py3.9-macosx-11-x86_64.egg/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/usr/local/lib/python3.9/site-packages/pyobjc_framework_Cocoa-7.3-py3.9-macosx-11-x86_64.egg/CoreFoundation/__init__.py", line 9, in <module>
    import objc
  File "/usr/local/lib/python3.9/site-packages/pyobjc_core-7.2-py3.9-macosx-11-x86_64.egg/objc/__init__.py", line 29, in <module>
    from ._bridgesupport import *  # noqa: F401, F403, E402
  File "/usr/local/lib/python3.9/site-packages/pyobjc_core-7.2-py3.9-macosx-11-x86_64.egg/objc/_bridgesupport.py", line 13, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyobjc-core==7.2' distribution was not found and is required by osxmetadata

**Comment by RhetTbull** [comment]
@john-catalano  I don't have a machine that will run Monterey so I'm kind of shooting in the dark but it looks like there's a missing dependency.  I made a small tweak to osxmetadata -- try `pipx upgrade osxmetadata` assuming you installed it via pipx and try again.  (Should be version 0.99.35).  Let me know if you still get the error.

**Comment by john-catalano** [comment]
Thank you, but even after the upgrade...

john@mac ~ % pipx upgrade osxmetadata
upgraded package osxmetadata from 0.99.34 to 0.99.35 (location:
/Users/john/.local/pipx/venvs/osxmetadata)

...it looks the same.

john@mac ~ % osxmetadata
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyobjc-core 7.2 (/usr/local/lib/python3.9/site-packages/pyobjc_core-7.2-py3.9-macosx-11-x86_64.egg), Requirement.parse('pyobjc-core>=7.3'), {'pyobjc-framework-Cocoa'})

...

**Comment by RhetTbull** [comment]
Try the following steps and let me know the result:

- `pipx uninstall osxmetadata`
- `pipx install osxmetadata`
- `pipx inject osxmetadata pyobjc==7.3`
- `osxmetadata`

**Comment by john-catalano** [comment]
Done, but I still have errors. Thank you for working on this.

Last login: Tue Nov  2 14:41:41 on ttys000
john@mac ~ % pipx uninstall osxmetadata
uninstalled osxmetadata! ✨ 🌟 ✨
john@mac ~ % pipx install osxmetadata
⚠️  Note: osxmetadata was already on your PATH at /usr/local/bin/osxmetadata
  installed package osxmetadata 0.99.35, Python 3.10.0
  These apps are now globally available
    - osxmetadata
done! ✨ 🌟 ✨
john@mac ~ % pipx inject osxmetadata pyobjc==7.3
  injected package pyobjc into venv osxmetadata
done! ✨ 🌟 ✨
john@mac ~ % osxmetadata
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyobjc-core 7.2 (/usr/local/lib/python3.9/site-packages/pyobjc_core-7.2-py3.9-macosx-11-x86_64.egg), Requirement.parse('pyobjc-core>=7.3'), {'pyobjc-framework-Cocoa'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osxmetadata", line 33, in <module>
    sys.exit(load_entry_point('osxmetadata==0.99.14', 'console_scripts', 'osxmetadata')())
  File "/usr/local/bin/osxmetadata", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/osxmetadata-0.99.14-py3.9.egg/osxmetadata/__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/osxmetadata-0.99.14-py3.9.egg/osxmetadata/osxmetadata.py", line 16, in <module>
  File "/usr/local/lib/python3.9/site-packages/py_applescript-1.0.2-py3.9.egg/applescript/__init__.py", line 5, in <module>
    from Foundation import NSAppleScript, NSAppleEventDescriptor, NSURL, \
  File "/usr/local/lib/python3.9/site-packages/pyobjc_framework_Cocoa-7.3-py3.9-macosx-11-x86_64.egg/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/usr/local/lib/python3.9/site-packages/pyobjc_framework_Cocoa-7.3-py3.9-macosx-11-x86_64.egg/CoreFoundation/__init__.py", line 9, in <module>
    import objc
  File "/usr/local/lib/python3.9/site-packages/pyobjc_core-7.2-py3.9-macosx-11-x86_64.egg/objc/__init__.py", line 29, in <module>
    from ._bridgesupport import *  # noqa: F401, F403, E402
  File "/usr/local/lib/python3.9/site-packages/pyobjc_core-7.2-py3.9-macosx-11-x86_64.egg/objc/_bridgesupport.py", line 13, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyobjc-core==7.2' distribution was not found and is required by osxmetadata
john@mac ~ %

**Comment by RhetTbull** [comment]
I suspect you have two copies of osxmetadata installed. Try `which osxmetadata`. If it says `/usr/local/bin/osxmetadata`, try `rm /usr/local/bin/osxmetadata` and try running it again.

**Comment by john-catalano** [comment]
That was it! Once I ran /usr/local/bin/osxmetadata, I could successfully execute osxmetadata.

Thank you.
